### ISSUE TITLE
Is it possible to deploy the HPCTS into an EC2 instance?

### ISSUE THREAD

**Issue by SajidK25** [ubccr/hpc-toolset-tutorial#148]
I have tried several times to deploy this repository into an AWS EC2 instance. I just changed the published IP of docker-compose.yml file to `0.0.0.0` as following:-
```
// --------
frontend:
    image: hpcts:slurm-${HPCTS_VERSION}
    command: ["frontend"]
    hostname: frontend
    container_name: frontend
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    ports:
      - "0.0.0.0:6222:22"
    depends_on:
      - ldap
      - slurmctld

  coldfront:
    image: hpcts:coldfront-${HPCTS_VERSION}
    build:
      context: ./coldfront
      args:
        HPCTS_VERSION: $HPCTS_VERSION
    command: ["serve"]
    hostname: coldfront
    container_name: coldfront
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
      - srv_www:/srv/www
    expose:
      - "22"
    ports:
      - "0.0.0.0:2443:443"
    depends_on:
      - ldap
      - mysql
      - frontend

  ondemand:
    image: hpcts:ondemand-${HPCTS_VERSION}
    build:
      context: ./ondemand
      args:
        HPCTS_VERSION: $HPCTS_VERSION
    command: ["serve"]
    hostname: ondemand
    container_name: ondemand
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
    ports:
      - "0.0.0.0:3443:3443"
      - "0.0.0.0:5554:5554"
    depends_on:
      - ldap
      - frontend

  xdmod:
    image: hpcts:xdmod-${HPCTS_VERSION}
    build:
      context: ./xdmod
      args:
        HPCTS_VERSION: $HPCTS_VERSION
    command: ["serve"]
    hostname: xdmod
    container_name: xdmod
    networks:
      - compute
    volumes:
      - etc_xdmod:/etc/xdmod
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
    ports:
      - "0.0.0.0:4443:443"
    depends_on:
      - mongodb
      - ldap
      - mysql
      - frontend
 // --------
``` 
**After executed** `./hpcts start`, **all services were built successfully.**
```
sajid@ubuntu-s-4vcpu-8gb-blr1-01:~/hpc-toolset-tutorial$ docker image list
REPOSITORY   TAG                 IMAGE ID       CREATED        SIZE
hpcts        xdmod-2022.07       8afba6346001   7 hours ago    5.2GB
hpcts        ondemand-2022.07    361496f24072   8 hours ago    4.63GB
hpcts        coldfront-2022.07   9c59638239c4   8 hours ago    4.13GB
hpcts        slurm-2022.07       982417903ebd   23 hours ago   3.83GB
hpcts        base-2022.07        e8b968f77f70   24 hours ago   393MB
hpcts        ldap-2022.07        c21746a48540   24 hours ago   257MB
mongo        5.0                 d98599fdfd65   6 days ago     696MB
mariadb      10.3                cd091d34afbb   6 days ago     387MB
sajid@ubuntu-s-4vcpu-8gb-blr1-01:~/hpc-toolset-tutorial$ docker container list
CONTAINER ID   IMAGE                     COMMAND                  CREATED       STATUS       PORTS                                                    NAMES
ef0cbf65e5ad   mongo:5.0                 "docker-entrypoint.s…"   7 hours ago   Up 7 hours   27017/tcp                                                mongodb
52b13d02c780   hpcts:xdmod-2022.07       "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   22/tcp, 0.0.0.0:4443->443/tcp                            xdmod
29153626bb00   hpcts:ondemand-2022.07    "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   0.0.0.0:3443->3443/tcp, 22/tcp, 0.0.0.0:5554->5554/tcp   ondemand
543296890edb   hpcts:coldfront-2022.07   "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   22/tcp, 0.0.0.0:2443->443/tcp                            coldfront
b356187459e9   hpcts:slurm-2022.07       "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   22/tcp, 6818/tcp                                         cpn01
892a379102e0   hpcts:slurm-2022.07       "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   0.0.0.0:6222->22/tcp                                     frontend
740fd7111023   hpcts:slurm-2022.07       "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   22/tcp, 6818/tcp                                         cpn02
8b534413f47f   hpcts:slurm-2022.07       "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   22/tcp, 6817/tcp                                         slurmctld
2e431a7eaea5   hpcts:slurm-2022.07       "/usr/local/bin/entr…"   7 hours ago   Up 7 hours   22/tcp, 6819/tcp                                         slurmdbd
aebd4868473e   mariadb:10.3              "docker-entrypoint.s…"   7 hours ago   Up 7 hours   3306/tcp                                                 mysql
9c13c02dd691   hpcts:ldap-2022.07        "/container/tool/run"    7 hours ago   Up 7 hours   389/tcp, 636/tcp                                         ldap
```
However, I can accesss all applications  except **OnDemand*.

**Here is the OnDemand's log `docker-compose logs -f ondemand` :-**
```
ondemand     | ---> Populating /etc/ssh/ssh_known_hosts from frontend for ondemand...
ondemand     | # frontend:22 SSH-2.0-OpenSSH_8.0
ondemand     | # frontend:22 SSH-2.0-OpenSSH_8.0
ondemand     | # frontend:22 SSH-2.0-OpenSSH_8.0
ondemand     | ---> Starting SSSD on ondemand ...
ondemand     | ---> Cleaning NGINX ...
ondemand     | (2022-08-08 21:58:44): [sssd] [server_setup] (0x1f7c0): Starting with debug level = 0x0070
ondemand     | (2022-08-08 21:58:44): [be[implicit_files]] [server_setup] (0x1f7c0): Starting with debug level = 0x0070
ondemand     | (2022-08-08 21:58:44): [be[default]] [server_setup] (0x1f7c0): Starting with debug level = 0x0070
ondemand     | (2022-08-08 21:58:44): [nss] [server_setup] (0x1f7c0): Starting with debug level = 0x0070
ondemand     | (2022-08-08 21:58:44): [pam] [server_setup] (0x1f7c0): Starting with debug level = 0x0070
ondemand     | ---> Starting the MUNGE Authentication service (munged) on ondemand ...
ondemand     | ---> Starting sshd on ondemand...
ondemand     | ---> Running update ood portal...
ondemand     | cp -p /etc/pki/tls/certs/localhost.crt /etc/ood/dex/localhost.crt
ondemand     | chown ondemand-dex:ondemand-dex /etc/ood/dex/localhost.crt
ondemand     | cp -p /etc/pki/tls/private/localhost.key /etc/ood/dex/localhost.key
ondemand     | chown ondemand-dex:ondemand-dex /etc/ood/dex/localhost.key
ondemand     | No change in Apache config.
ondemand     | No change in the Dex config.
ondemand     | Completed successfully!
ondemand     | ---> Starting ondemand-dex...
ondemand     | ---> Starting ondemand httpd24...
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="config issuer: https://hpcts.t99ltd.info:5554"
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="config storage: sqlite3"
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="config static client: OnDemand"
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="config connector: ldap"
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="config skipping approval screen"
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="listening (http/telemetry) on 0.0.0.0:5558"
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="listening (http) on 0.0.0.0:5556"
ondemand     | time="2022-08-08T21:58:45Z" level=info msg="listening (https) on 0.0.0.0:5554"
ondemand     | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.30.0.9. Set the 'ServerName' directive globally to suppress this message
ondemand     | time="2022-08-09T03:20:15Z" level=info msg="keys expired, rotating"
ondemand     | time="2022-08-09T03:20:15Z" level=info msg="keys rotated, next rotation: 2022-08-09 09:20:15.515348558 +0000 UTC"
ondemand     | 2022-08-09 04:43:24.556688 I | http: TLS handshake error from 59.153.103.253:46942: remote error: tls: unknown certificate
```
I have modified the `ondemand/install.sh` as following:-
```
#!/bin/bash
set -e

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

log_info() {
  printf "\n\e[0;35m $1\e[0m\n\n"
}

log_info "Setting up Ondemand"
mkdir -p /etc/ood/config/clusters.d
mkdir -p /etc/ood/config/apps/shell
mkdir -p /etc/ood/config/apps/bc_desktop
mkdir -p /etc/ood/config/apps/dashboard
mkdir -p /etc/ood/config/apps/myjobs/templates
echo "DEFAULT_SSHHOST=frontend" > /etc/ood/config/apps/shell/env
echo "OOD_DEFAULT_SSHHOST=frontend" >> /etc/ood/config/apps/shell/env
echo "OOD_SSHHOST_ALLOWLIST=ondemand:cpn01:cpn02" >> /etc/ood/config/apps/shell/env
echo "OOD_DEV_SSH_HOST=ondemand" >> /etc/ood/config/apps/dashboard/env
echo "MOTD_PATH=/etc/motd" >> /etc/ood/config/apps/dashboard/env
echo "MOTD_FORMAT=markdown" >> /etc/ood/config/apps/dashboard/env
echo "OOD_BC_DYNAMIC_JS=1" >> /etc/ood/config/apps/dashboard/env

log_info "Configuring Ondemand ood_portal.yml .."

tee /etc/ood/config/ood_portal.yml <<EOF
---
#
# Portal configuration
#
listen_addr_port:
  - '3443'
servername: hpcts.t99ltd.info
port: 3443
ssl:
   - 'SSLCertificateFile "/etc/pki/tls/certs/localhost.crt"'
   - 'SSLCertificateKeyFile "/etc/pki/tls/private/localhost.key"'
node_uri: "/node"
rnode_uri: "/rnode"
oidc_scope: "openid profile email groups"
dex:
  client_redirect_uris:
    - "https://hpcts.t99ltd.com:4443/simplesaml/module.php/authoidcoauth2/linkback.php"
    - "https://hpcts.t99ltd.com:2443/oidc/callback/"
  client_secret: 334389048b872a533002b34d73f8c29fd09efc50
  client_id: hpcts.t99ltd.com
  connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: ldap:636
        insecureSkipVerify: true
        bindDN: cn=admin,dc=example,dc=org
        bindPW: admin
        userSearch:
          baseDN: ou=People,dc=example,dc=org
          filter: "(objectClass=posixAccount)"
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: gecos
          preferredUsernameAttr: uid
        groupSearch:
          baseDN: ou=Groups,dc=example,dc=org
          filter: "(objectClass=posixGroup)"
          userMatchers:
            - userAttr: DN
              groupAttr: member
          nameAttr: cn
  # This is the default, but illustrating how to change
  frontend:
    theme: ondemand
EOF

log_info "Generating new httpd24 and dex configs.."
/opt/ood/ood-portal-generator/sbin/update_ood_portal

log_info "Adding new theme to dex"
sed -i "s/theme: ondemand/theme: hpc-coop/g" /etc/ood/dex/config.yaml

dnf clean all
rm -rf /var/cache/dnf

log_info "Cloning repos to assist with app development.."
mkdir -p /var/git
git clone https://github.com/OSC/bc_example_jupyter.git --bare /var/git/bc_example_jupyter
git clone https://github.com/OSC/ood-example-ps.git --bare /var/git/ood-example-ps

log_info "Enabling app development for hpcadmin..."
mkdir -p /var/www/ood/apps/dev/hpcadmin
ln -s /home/hpcadmin/ondemand/dev /var/www/ood/apps/dev/hpcadmin/gateway
echo 'if [[ ${HOSTNAME} == ondemand ]]; then source scl_source enable ondemand; fi' >> /home/hpcadmin/.bash_profile
```
**when I tried to access Ondemand using this URL : https://hpcts.t99ltd.com:3443, follwin error raised : -**
![alt Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log](https://ibb.co/hZ5qGfK)

My question:-

1. Is it possible to override the default localhost configuration?
2. If possible what I am doing wrong?
