### ISSUE TITLE
HPC Desktop does not start, HOME not defined

### ISSUE THREAD

**Issue by psuter80** [ubccr/hpc-toolset-tutorial#209]
I just cloned this repo and ran the ./hpcts start command for the first time. ood is running and i can start jobs and run an interactive jupyter notebook session, bu tthe HPC Desktop fails to start. 

the output.log shows this: 
```
Setting VNC password...
Error: no HOME environment variable
Starting VNC server...
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
vncserver: The HOME environment variable is not set.
Cleaning up...
vncserver: The HOME environment variable is not set.
```
in the jupyter notebook session, when i start a shell, the $HOME variable is also not set.

**Comment by alexschroeter** [comment]
Should be addressed in https://github.com/ubccr/hpc-toolset-tutorial/pull/223 if you want to test it.

**Comment by jeremyfix** [comment]
Indeed you are right , and we can fix it by :

- From the host on which you run docker  : 

```
docker exec -it ondemand bash
```

- In the shell that opens, we run the command mentioned in the post of @OliverTUBAF  :

```
cd /etc/ood/
vim clusters.d/hpc.yml
```

and then add the missing `export HOME=....` variable definition as suggested in the PR #223 (among other things) :

```
[root@ondemand config]# cat clusters.d/hpc.yml

---
v2:
  metadata:
    title: "HPC Cluster"
  login:
    host: "frontend"
  job:
    adapter: "slurm"
    cluster: "hpc"
    bin: "/usr/bin"
    conf: "/etc/slurm/slurm.conf"
  batch_connect:
    vnc:
      script_wrapper: |
        export PATH="/opt/TurboVNC/bin:$PATH"
        export WEBSOCKIFY_CMD="/usr/local/bin/websockify"
        export HOME="${HOME:-$(eval echo ~$(whoami))}"
        %s
  custom:
    xdmod:
      resource_id: 1

```


- Then we log (Ctrl + D) , and `docker restart ondemand`
